# -*- coding: utf-8 -*-
"""Rent_Data_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cp1QY4neAxO6wdzlTWqv_98f6F8yErqj

# Proyek Analisis Data: RENTAL BIKE
- **Nama:** Brigade Mahendra
- **Email:** m180b4ky0874@bangkit.academy
- **ID Dicoding:** brigade_mahendra

## Menentukan Pertanyaan Bisnis

- Bagaimana perbedaan rental ketika weekday, holiday, dan workingday setiap bulannya?
- Apakah pengaruh cuaca terhadap kondisi rental ketika weekday, holiday, dan workingday?
- Apakah pengaruh musim terhadap kondisi rental ketika weekday, holiday, dan workingday?
- Apakah terdapat perbedaan jam rental ketika weekday, holiday, workingday?

## Import Semua Packages/Library yang Digunakan
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""## Data Wrangling

### Gathering Data

Pembukaan data **"Hari"**
"""

hari_df = pd.read_csv("https://raw.githubusercontent.com/Esylum/Rental-Bike-Analysis/refs/heads/main/day.csv")
hari_df.head()

"""Pembukaan data **"Jam"**"""

jam_df = pd.read_csv("https://raw.githubusercontent.com/Esylum/Rental-Bike-Analysis/refs/heads/main/hour.csv")
jam_df.head()

"""**Insight:**
- Melakukan pemanggilan data **Day** dengan pendefinisian **hari_df** dan data **Hour** dengan pendefinisian **jam_df** dengan fitur **.pd.read_csv()**.
- Melakukan command **.head()** untuk menampilkan baris dan kolom awal data.

### Assessing Data

##Menilai tabel **hari_df**

1. Memeriksa tipe data
"""

hari_df.info()

"""2. Menilai jumlah data yang hilang"""

hari_df.isna().sum()

"""3. Menilai jumlah data duplikat"""

print("Jumlah data duplikat: ", hari_df.duplicated().sum())

"""4. Memeriksa keanehan data numerik"""

hari_df.describe()

"""##Menilai tabel **jam_df**

1. Memeriksa tipe data
"""

jam_df.info()

"""2. Menilai jumlah data yang hilang"""

jam_df.isna().sum()

"""3. Menilai jumlah data duplikat"""

print("Jumlah data duplikat:", jam_df.duplicated().sum())

"""4. Memeriksa keanehan data numerik"""

jam_df.describe()

"""**Insight:**
- Memeriksa tipe data yang digunakan menggunakan fitur **.info()**
- Menilai jumlah data yang hilang dengan fitur **.isna().sum()**, jumlah data yang terduplikat dengan fitur **.duplicate().sum()**
- Memeriksa keanehan data numerik pada kedua dataset dengan fitur **.describe()**

### Cleaning Data

## Filter **hari_df**

1. Menghapus kolom data yang tidak digunakan
    - Instant: tidak memberikan data mendukung pertanyaan
    - Windspeed: tidak ditanyakan dalam pertanyaan
    - Casual: tidak ditanyakan dalam pertanyaan
    - Registered: tidak ditanyakan dalam pertanyaan
    - Hum: tidak ditanyakan dalam pertanyaan
    - temp: tidak ditanyakan dalam pertanyaan
    - atemp: tidak ditanyakan dalam pertanyaan
    - hum: tidak ditanyakan dalam pertanyaan
"""

hari_df.drop(columns=[
    'instant', 'windspeed', 'casual',
    'registered', 'hum', 'temp', 'atemp', 'yr'
    ], inplace = True)
hari_df.head()

"""2. Mengubah nama untuk setiap kolom data yang digunakan
    - Mempermudah pemanggilan data
    - Mempermudah pembacaan data
"""

hari_df.rename(columns = {
    'dteday':'tanggal',
    'mnth':'bulan',
    'weathersit':'cuaca',
    'season':'musim',
    'cnt':'jumlah'
    }, inplace = True)
hari_df.head()

"""3. Mengubah variabel data dari numerik menjadi keterangan
    - bulan = Januari - Desember
    - weekday = Senin - Minggu
    - workingday = Senin - Jumat
    - Musim = Spring, Summer, Fall, Winter
    - Weather = Cerah, Berawan, Hujan, Badai
"""

hari_df['bulan'] = hari_df['bulan'].map({
    1: 'Januari', 2:'Februari', 3:'Maret',
    4:'April', 5:'Mei', 6:'Juni', 7:'Juli',
    8:'Agustus', 9:'September', 10:'Oktober',
    11:'November', 12:'Desember'
})

hari_df['musim'] = hari_df['musim'].map({
    1:'Spring', 2:'Summer', 3:'Fall', 4:'Winter'
})

hari_df['cuaca'] = hari_df['cuaca'].map({
    1:'Cerah', 2:'Berawan', 3:'Hujan', 4:'Badai'
})

"""4. Mengubah tipe data tanggal menjadi **datetime()**"""

hari_df['tanggal'] = pd.to_datetime(hari_df['tanggal'])
hari_df.info()

"""5. Mengubah tipe data menjadi category"""

hari_df['bulan'] = hari_df.bulan.astype('category')
hari_df['musim'] = hari_df.musim.astype('category')
hari_df['cuaca'] = hari_df.cuaca.astype('category')
hari_df.info()

"""##Filter **jam_df**

1. Menghapus kolom data yang tidak digunakan
    - Instant: tidak memberikan data mendukung pertanyaan
    - Windspeed: tidak ditanyakan dalam pertanyaan
    - Casual: tidak ditanyakan dalam pertanyaan
    - Registered: tidak ditanyakan dalam pertanyaan
    - Hum: tidak ditanyakan dalam pertanyaan
    - Temp: tidak ditanyakan dalam pertanyaan
    - atemp: tidak ditanyakan dalam pertanyaan
    - hum: tidak ditanyakan dalam pertanyaan
    - Month: tidak ditanyakan dalam pertanyaan
    - Season: tidak ditanyakan dalam pertanyaan
    - Weathersit: tidak ditanyakan dalam pertanyaan
"""

jam_df.drop(columns=[
    'instant', 'windspeed', 'casual',
    'registered', 'hum', 'temp', 'atemp', 'yr',
    'mnth', 'season', 'weathersit'
    ], inplace = True)
jam_df.head()

"""2. Mengubah nama untuk setiap kolom data yang digunakan
    - Mempermudah pemanggilan data
    - Mempermudah pembacaan data
"""

jam_df.rename(columns = {
    'dteday':'tanggal',
    'hr':'jam',
    'cnt':'jumlah'
    }, inplace = True)
jam_df.head()

"""3. Mengubah tipe data tanggal menjadi **datetime()**"""

jam_df['tanggal'] = pd.to_datetime(jam_df['tanggal'])
jam_df.info()

"""## Exploratory Data Analysis (EDA)

### Explore data **hari_df**

# Mengelompokkan data **weekday**, **workingday**, **holiday**

1. Berdasarkan **bulan**
"""

hari_df.groupby(by='bulan', observed=True).agg({
    'weekday': ['max', 'min', 'mean', 'sum'],
    'workingday':['max', 'min', 'mean', 'sum'],
    'holiday': ['max', 'min', 'mean', 'sum']
})

"""2. Berdasarkan **musim**"""

hari_df.groupby(by='musim', observed=True).agg({
    'weekday': ['max', 'min', 'mean', 'sum'],
    'workingday':['max', 'min', 'mean', 'sum'],
    'holiday': ['max', 'min', 'mean', 'sum']
})

"""3. Berdasarkan **cuaca**"""

hari_df.groupby(by='cuaca', observed=True).agg({
    'weekday': ['max', 'min', 'mean', 'sum'],
    'workingday':['max', 'min', 'mean', 'sum'],
    'holiday': ['max', 'min', 'mean', 'sum']
})

"""# Hubungan antara **weekday**, **workingday**, **holiday**

Visualisasi **heatmap** korelasi data **hari_df**
"""

correlation_matrix = hari_df.corr(numeric_only = True)

sns.heatmap(correlation_matrix, annot = True,
            cmap = 'coolwarm', fmt = ".2f")
plt.title("Heatmap Korelasi")
plt.show()

"""### Explore data **jam_df**

# Mengelompokkan data weekday, workingday, holiday
"""

jam_df.groupby(by='jam', observed=True).agg({
    'weekday': ['max', 'min', 'mean', 'sum'],
    'workingday':['max', 'min', 'mean', 'sum'],
    'holiday': ['max', 'min', 'mean', 'sum']
})

"""Visualisasi **heatmap** korelasi data **jam_df**"""

correlation_matrix = jam_df.corr(numeric_only = True)

sns.heatmap(correlation_matrix, annot = True,
            cmap = 'coolwarm', fmt = ".2f")
plt.title("Heatmap Korelasi")
plt.show()

"""**Insight:**
* Data **hari_df**
  1. Holiday
    - Korelasi dengan weekday (Hari Kerja): -0.10, artinya ada korelasi negatif yang sangat lemah. Ini menunjukkan bahwa pada hari libur, hari kerja memiliki sedikit kecenderungan untuk berkurang, meskipun korelasinya sangat lemah.
    - Korelasi dengan workingday (Hari Kerja Aktif): -0.25, ini adalah korelasi negatif yang lebih kuat dibandingkan dengan weekday. Ini menunjukkan bahwa ketika ada libur, jumlah hari kerja aktif berkurang lebih signifikan.
    - Korelasi dengan jumlah: -0.07, korelasi yang sangat lemah dan negatif, menunjukkan hampir tidak ada hubungan antara hari libur dan variabel jumlah.
  2. Weekday
    - Korelasi dengan holiday (Libur): -0.10, seperti dijelaskan di atas, ada hubungan negatif yang sangat lemah antara hari kerja dan hari libur.
    - Korelasi dengan workingday (Hari Kerja Aktif): 0.04, hubungan positif yang sangat lemah. Ini menunjukkan bahwa jumlah hari kerja aktif sedikit meningkat pada hari kerja, tetapi korelasinya sangat kecil.
    - Korelasi dengan jumlah: 0.07, hubungan positif yang lemah, menunjukkan bahwa jumlah (mungkin jumlah total kerja atau aktivitas) sedikit meningkat pada hari kerja.
  3. Workingday
    - Korelasi dengan holiday (Libur): -0.25, korelasi negatif yang signifikan, menunjukkan bahwa ketika ada hari libur, jumlah hari kerja aktif cenderung berkurang.
    - Korelasi dengan weekday (Hari Kerja): 0.04, hubungan yang sangat lemah, menunjukkan bahwa tidak ada hubungan yang signifikan antara hari kerja biasa dan hari kerja aktif.
    - Korelasi dengan jumlah: 0.06, hubungan positif yang lemah, menunjukkan bahwa hari kerja aktif sedikit berhubungan dengan peningkatan dalam jumlah.
* Data **jam_df**
  1. Korelasi Jam dengan Workingday (0.00):
    - Nilai korelasinya 0.00, yang berarti tidak ada hubungan linear antara jam dan workingday.
  2. Korelasi Jam dengan Weekday (-0.00):
    - Nilai korelasinya -0.00, yang sangat dekat dengan nol. Hal ini mengindikasikan bahwa tidak ada hubungan linear antara jam dan apakah hari tersebut adalah hari kerja biasa (weekday).
  3. Korelasi Jam dengan Holiday (0.00):
    - Nilai korelasinya 0.00, yang menunjukkan tidak ada hubungan antara jam dan hari libur (holiday).

## Visualization & Explanatory Analysis

### Pertanyaan 1: Bagaimana perbedaan rental ketika weekday, holiday, dan workingday setiap bulannya?
"""

hari_df_melted = pd.melt(hari_df, id_vars=['bulan'], value_vars=['weekday', 'workingday', 'holiday'],
                         var_name='Type', value_name='Value')

plt.figure(figsize = (11,6))

sns.barplot(x='bulan', y='Value', hue='Type', data=hari_df_melted)

plt.title('Perbandingan rental bulanan weekday, workingday, dan holiday')
plt.xlabel('Bulan')
plt.ylabel('Value')
plt.show()

"""### Pertanyaan 2: Apakah pengaruh cuaca terhadap kondisi rental ketika weekday, holiday, dan workingday?"""

hari_df_melted = pd.melt(hari_df, id_vars=['cuaca'], value_vars=['weekday', 'workingday', 'holiday'],
                         var_name='Type', value_name='Value')

plt.figure(figsize = (11,6))

sns.barplot(x='cuaca', y='Value', hue='Type', data=hari_df_melted)

plt.title('Pengaruh cuaca terhadap rental pada weekday, workingday, dan holiday')
plt.xlabel('Cuaca')
plt.ylabel('Value')
plt.show()

"""### Pertanyaan 3: Apakah pengaruh musim terhadap kondisi rental ketika weekday, holiday, dan workingday?"""

hari_df_melted = pd.melt(hari_df, id_vars=['musim'], value_vars=['weekday', 'workingday', 'holiday'],
                         var_name='Type', value_name='Value')

plt.figure(figsize = (11,6))

sns.barplot(x='musim', y='Value', hue='Type', data=hari_df_melted)

plt.title('Pengaruh cuaca terhadap rental pada weekday, workingday, dan holiday')
plt.xlabel('Musim')
plt.ylabel('Value')
plt.show()

"""**Insight:**
1. Perbandingan bulan
  - Weekday memiliki jumlah rental tertinggi di semua bulan dibandingkan dengan hari workingday dan holiday. Hal ini konsisten di seluruh bulan, dengan rata-rata rental lebih dari 3.0.
  - Workingday memiliki jumlah rental kedua tertinggi, namun jauh di bawah weekday. Dalam semua bulan, perbedaan ini cukup signifikan.
  - Holiday memiliki jumlah rental yang paling rendah dibandingkan dengan kedua tipe hari lainnya (weekday dan workingday). Pada bulan tertentu, jumlah rental di hari libur bahkan mendekati nol.
  - Pola dari bulan ke bulan cukup konsisten, dengan variasi kecil pada tingkat rental di semua tipe hari. Tidak ada perbedaan mencolok antara bulan yang satu dengan yang lain.
2. Pengaruh cuaca
  - Saat Weekday, cuaca berawan, cerah, dan hujan tidak menunjukkan perbedaan signifikan terhadap jumlah rental pada weekday. Jumlah rental tetap tinggi di sekitar 3.0–3.5, tanpa perubahan drastis berdasarkan cuaca.
  - Pada workingday, jumlah rental lebih rendah dibandingkan weekday untuk semua kondisi cuaca. Cuaca berawan dan hujan sedikit mengurangi jumlah rental, tetapi tidak terlalu drastis. Cuaca cerah menunjukkan jumlah rental yang hampir sama dengan cuaca berawan dan hujan, meskipun sedikit lebih rendah.
  - Pada holiday, jumlah rental sangat rendah, terutama ketika cuaca cerah dan hujan, hampir mendekati nol. Cuaca berawan juga menunjukkan jumlah rental yang rendah, tetapi sedikit lebih tinggi dibandingkan cuaca lainnya.
3. Pengaruh musim
  - Weekday, di semua musim (Fall, Spring, Summer, Winter), jumlah rental pada weekday selalu berada pada level tertinggi, mendekati atau lebih dari 3. Tidak terlihat perbedaan signifikan dalam jumlah rental pada weekday antara musim-musim yang berbeda. Setiap musim menunjukkan tren rental yang konsisten.
  - Rental pada workingday lebih rendah dibandingkan dengan weekday, namun konsisten di semua musim. Musim Fall dan Summer menunjukkan rental sedikit lebih tinggi dibandingkan Spring dan Winter.
  - Holiday, seperti grafik sebelumnya, rental pada holiday berada pada level terendah di semua musim. Musim Spring dan Summer tampaknya memiliki jumlah rental terendah pada holiday, dengan hampir nol aktivitas rental, sementara musim Fall dan Winter memiliki jumlah yang sedikit lebih tinggi, meski tetap sangat rendah.

## Conclusion

- Conclution pertanyaan 1: Weekday adalah hari yang paling banyak digunakan untuk rental dibandingkan dengan workingday dan holiday. Holiday menunjukkan jumlah rental yang sangat rendah, mengindikasikan bahwa mungkin lebih sedikit orang yang melakukan rental pada hari libur. Perbandingan rental ini stabil di setiap bulan, menunjukkan pola yang tetap.
- Conclution pertanyaan 2: Weekday tetap menjadi hari dengan rental tertinggi, terlepas dari kondisi cuaca. Cuaca cerah dan hujan menunjukkan pengaruh yang lebih besar dalam menurunkan jumlah rental pada workingday dan holiday, terutama pada hari libur. Holiday memiliki jumlah rental yang sangat rendah untuk semua kondisi cuaca, menunjukkan bahwa cuaca mungkin lebih berpengaruh pada hari-hari tersebut.
- Conclution pertanyaan 3: Weekday tetap menjadi hari dengan rental tertinggi di semua musim, tanpa perubahan signifikan antara musim yang satu dengan yang lain. Musim tampaknya tidak memengaruhi jumlah rental secara signifikan pada weekday atau workingday. Holiday terus menunjukkan rental yang rendah di semua musim, dengan musim Spring dan Summer memiliki rental yang paling rendah.Tidak ada musim tertentu yang secara drastis meningkatkan atau menurunkan jumlah rental, yang menunjukkan bahwa faktor musim tidak memiliki pengaruh besar pada pola rental, terutama pada weekday.
- Conclution pertanyaan 4: Variabel jam memiliki korelasi positif yang cukup signifikan dengan jumlah (0.39), yang menunjukkan bahwa ada hubungan positif antara jam dan jumlah total. Holiday memiliki korelasi negatif dengan workingday (-0.25), yang cukup logis karena hari libur tidak termasuk dalam hari kerja. Tidak ada hubungan yang sangat kuat antara variabel lainnya, karena kebanyakan dari korelasi lainnya mendekati nol, menunjukkan hubungan yang lemah atau tidak signifikan antara variabel-variabel tersebut.
"""