# -*- coding: utf-8 -*-
"""dashboard.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yUEvGQNQz7CG_CdiVhtfPVxOb2V6SIvZ
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

# Set style seaborn
sns.set(style='dark')

#Menyiapkan data hari_df
hari_df = pd.read_csv("Dashboard/day.csv")
hari_df.head()

#Menyiapkan data jam_df
jam_df = pd.read_csv("Dashboard/hour.csv")
jam_df.head()

#Menghapus kolom tidak perlu pada hari_df
hari_df.drop(columns=[
    'instant', 'windspeed', 'casual',
    'registered', 'hum', 'temp', 'atemp', 'yr'
    ], inplace = True)

#Menghapus kolom tidak perlu pada jam_df
jam_df.drop(columns=[
    'instant', 'windspeed', 'casual',
    'registered', 'hum', 'temp', 'atemp', 'yr',
    'mnth', 'season', 'weathersit'
    ], inplace = True)
jam_df.head()

#Mengubah nama kolom hari_df
hari_df.rename(columns = {
    'dteday':'tanggal',
    'mnth':'bulan',
    'weathersit':'cuaca',
    'season':'musim',
    'cnt':'jumlah'
    }, inplace = True)
hari_df.head()

#Mengubah nama kolom jam_df
jam_df.rename(columns = {
    'dteday':'tanggal',
    'hr':'jam',
    'cnt':'jumlah'
    }, inplace = True)
jam_df.head()

#Mengubah angka menjadi keterangan
hari_df['bulan'] = hari_df['bulan'].map({
    1: 'Januari', 2:'Februari', 3:'Maret',
    4:'April', 5:'Mei', 6:'Juni', 7:'Juli',
    8:'Agustus', 9:'September', 10:'Oktober',
    11:'November', 10:'Desember'
})

hari_df['musim'] = hari_df['musim'].map({
    1:'Spring', 2:'Summer', 3:'Fall', 4:'Winter'
})

hari_df['cuaca'] = hari_df['cuaca'].map({
    1:'Cerah', 2:'Berawan', 3:'Hujan', 4:'Badai'
})

#Menyiapkan rental_harian_df
def create_rental_harian_df(df):
  rental_harian_df = df.groupby(by='tanggal').agg({
      'jumlah': 'sum'
      }).reset_index()
  return rental_harian_df

#Menyiapkan rental_harian_weekday_df
def create_rental_harian_weekday_df(df):
  rental_harian_weekday_df = df.groupby(by='tanggal').agg({
      'weekday': 'sum'
      }).reset_index()
  return rental_harian_weekday_df

#Menyiapkan rental_harian_holiday_df
def create_rental_harian_holiday_df(df):
  rental_harian_holiday_df = df.groupby(by='tanggal').agg({
      'holiday': 'sum'
      }).reset_index()
  return rental_harian_holiday_df

#Menyiapkan rental_harian_workingday_df
def create_rental_harian_workingday_df(df):
  rental_harian_workingday_df = df.groupby(by='tanggal').agg({
      'workingday': 'sum'
      }).reset_index()
  return rental_harian_workingday_df

# Menyiapkan rental_musiman_df
def create_rental_musiman_df(df):
  rental_musiman_df = df.groupby(by='musim')[['weekday', 'workingday', 'holiday']].sum().reset_index()
  return rental_musiman_df

# Menyiapkan rental_cuaca_df
def create_rental_cuaca_df(df):
  rental_cuaca_df = df.groupby(by='musim')[['weekday', 'workingday', 'holiday']].sum().reset_index()
  return rental_cuaca_df

# Menyiapkan monthly_rent_df
def create_rental_bulanan_df(df):
  rental_bulanan_df = df.groupby(by='bulan').agg({
      'jumlah': 'sum'
      })
  ordered_months = [
      'Januari', 'Februari', 'Maret',
      'April', 'Mei', 'Juni', 'Juli',
      'Agustus', 'September', 'Oktober',
      'November', 'Desember'
      ]
  rental_bulanan_df = rental_bulanan_df.reindex(ordered_months, fill_value=0)
  return rental_bulanan_df

# Membuat komponen filter
min_date = pd.to_datetime(hari_df['tanggal']).dt.date.min()
max_date = pd.to_datetime(hari_df['tanggal']).dt.date.max()

with st.sidebar:
  st.image('Dashboard/Esylum Rent.png')
    
# Mengambil start_date & end_date dari date_input
start_date, end_date = st.date_input(
    label='Rentang Waktu',
    min_value= min_date,
    max_value= max_date,
    value=[min_date, max_date])
main_df = hari_df[(hari_df['tanggal'] >= str(start_date)) &
                (hari_df['tanggal'] <= str(end_date))]

# Menyiapkan berbagai dataframe
rental_harian_df = create_rental_harian_df(main_df)
rental_harian_weekday_df = create_rental_harian_weekday_df(main_df)
rental_harian_holiday_df = create_rental_harian_holiday_df(main_df)
rental_harian_workingday_df = create_rental_harian_workingday_df(main_df)
rental_musiman_df = create_rental_musiman_df(main_df)
rental_cuaca_df = create_rental_cuaca_df(main_df)
rental_bulanan_df = create_rental_bulanan_df(main_df)

# Membuat Dashboard secara lengkap

# Membuat judul
st.header('Bike Rental Dashboard 🚲')

# Membuat jumlah penyewaan harian
st.subheader('Rental Harian')
col1, col2, col3, col4 = st.columns(4)

with col1:
    rental_harian_weekday = rental_harian_weekday_df['weekday'].sum()
    st.metric('Weekday User', value= rental_harian_weekday)

with col2:
    rental_harian_holiday = rental_harian_holiday_df['holiday'].sum()
    st.metric('Holiday User', value= rental_harian_holiday)

with col3:
    reate_rental_harian_workingday = reate_rental_harian_workingday_df['workingday'].sum()
    st.metric('Workingday User', value= rental_rental_harian_workingday)

with col4:
  rental_harian_total = rental_harian_df['jumlah'].sum()
  st.metric('Total User', value= rental_harian_total)

# Membuat jumlah penyewaan bulanan
hari_df_melted = pd.melt(hari_df, id_vars=['bulan'], value_vars=['weekday', 'workingday', 'holiday'],
                         var_name='Type', value_name='Value')

fig, ax = plt.subplots(figsize=(24, 8))

sns.barplot(x='bulan', y='Value', hue='Type', data=hari_df_melted)

for index, row in enumerate(rental_bulanan_df['jumlah']):
    ax.text(index, row + 1, str(row), ha='center', va='bottom', fontsize=12)

ax.tick_params(axis='x', labelsize=25, rotation=45)
ax.tick_params(axis='y', labelsize=20)
st.pyplot(fig)

# Membuat jumlah penyewaan berdasarkan musim
st.subheader('Rental Musiman')

hari_df_melted = pd.melt(hari_df, id_vars=['musim'], value_vars=['weekday', 'workingday', 'holiday'],
                         var_name='Type', value_name='Value')

fig, ax = plt.subplots(figsize=(16, 8))

sns.barplot(x='musim', y='Value', hue='Type', data=hari_df_melted)

for index, row in rental_musiman_df.iterrows():
    ax.text(index, row['weekday', 'workingday', 'holiday'], str(row['weekday', 'workingday', 'holiday']), ha='center', va='bottom', fontsize=12)

ax.set_xlabel(None)
ax.set_ylabel(None)
ax.tick_params(axis='x', labelsize=20, rotation=0)
ax.tick_params(axis='y', labelsize=15)
ax.legend()
st.pyplot(fig)

# Membuah jumlah penyewaan berdasarkan kondisi cuaca
st.subheader('Rental Cuaca')

hari_df_melted = pd.melt(hari_df, id_vars=['cuaca'], value_vars=['weekday', 'workingday', 'holiday'],
                         var_name='Type', value_name='Value')

fig, ax = plt.subplots(figsize=(16, 8))

sns.barplot(x='cuaca', y='Value', hue='Type', data=hari_df_melted)

for index, row in enumerate(rental_cuaca_df['jumlah']):
    ax.text(index, row + 1, str(row), ha='center', va='bottom', fontsize=12)

ax.set_xlabel(None)
ax.set_ylabel(None)
ax.tick_params(axis='x', labelsize=20)
ax.tick_params(axis='y', labelsize=15)
st.pyplot(fig)

st.caption('Copyright (c) Brigade Mahendra 2024')
